[supabase]
url = "https://fcpbttjlgccvqvleaodb.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjcGJ0dGpsZ2NjdnF2bGVhb2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMjcyNDAsImV4cCI6MjA4NzYwMzI0MH0.sOzHoVNH7ZzvO9fTYF7KXdZBfeswf4fWtt7nsxfbW8Y"